prepare:
  #Params for prepare stage
  seed : 0
  split : 0.2
train:
  #Params for train stage
  learning_rate: [0.0001, 0.001, 0.01]
  max_depth: [3, 5, 7]
  n_estimators: [200, 300, 500]
  min_child_weight: [3, 5, 7]
  subsample: [0.5, 0.7, 0.9]
  colsample_bytree: [0.5, 0.7, 0.9]
  objective: ['reg:squarederror']

  #Params for evaluate stage
  cv: 5
  n_jobs: -1
  verbose: 1

